name: todo_server
description: A server to store and retrieve todo items.
version: 1.0.0

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
# To add a dependency, search for the package you want,
# then follow the installation instructions on the package for
# installing via "Dart". The instruction will look like 
# "dart pub add package_name".
dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  supabase: ^1.11.10

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
